### ISSUE TITLE
Fade in transition

### ISSUE THREAD

**Issue by kristiechow** [dali-lab/tarsier-v2#51]

**Comment by Arkendorf** [comment]
I tried to use to the built-in VRTK_HeadsetFade script to implement the fade in transition as I got it working in the previous project, but it unfortunately did not work. Upon further research, I learned that, once again, this was due to our use of the lightweight render pipeline, as the script uses OnPostRender, which does not exist in LWRP. I will look for alternative solutions.

**Comment by Arkendorf** [comment]
So I've solved the rendering issue by just throwing a completely black prefab in front of the center eye camera, and fading in and out the prefab. However, the controllers often clip through this object, so I hide the controllers when fading. I'm almost complete, but the fading out does not work properly.
