### ISSUE TITLE
Start implementing arc back to hive and research ways to reduce motion sickness

### ISSUE THREAD

**Issue by kristiechow** [dali-lab/tarsier-v2#79]
Flying motion

**Comment by j-mai** [comment]
* https://uploadvr.com/how-ubisoft-created-eagle-flight-sickness/ : An eagle flying game with (supposedly) no nausea:
   * Used head as controller (direction)
   * Added a beak (because you normally see your nose in real life)
   * Dynamic blindness (vignetting)
   * Streaking particles to simulate wind rushing
   * fade-to-black on collisions
   * sound is huge part of it
